#!/bin/bash

# Define shell to use for this job
#$ -S /bin/bash

# Export all my environment variables into runtime context
#$ -V

#$ -terse

# User to inform
#$ -M elise.gueret@gmail.com

# Get a mail when the job begins, ends, or is suspended.
#$ -m bes

# Using current working directory
#$ -cwd

# Choose to run on a specific queue
#$ -q cemeb20.q

# Job hardware time limit
#$ -l h_rt=99:00:00

# Job name
#$ -N "run_gatk_"

# Standard output (you can use the option '-j y' which add stderr with sdtout)
#$ -o /home/egueret/Stage_UM_ISEM/Données_CRECHE/sge_lancer_PreProcessing.out

# Erreur output (don't use with the option '-j y')
#$ -e /home/egueret/Stage_UM_ISEM/Données_CRECHE/sge_lancer_PreProcessing.err

#Modules à charger pour que le script fonctionne
module load java1.8
module load java1.8_jre


#Lancer le pipeline

# Vérification de l'ordre et réassignment des valeurs de MAPQ : inutile CF stie web troubleshooting
# java -Dconfigfile=/home/egueret/Stage_UM_ISEM/Données_CRECHE/cromwell.conf -jar /home/egueret/tools/cromwell.jar run ReassignOneMappingQualityFilter.wdl -i ReassignOneMappingQualityFilter_inputs2.json

java -Dconfigfile=/home/egueret/Stage_UM_ISEM/Données_CRECHE/cromwell.conf -jar /home/egueret/tools/cromwell.jar run Data_PreProcessing.wdl -i Data_PreProcessing_inputs2.json