---
title: "essai-format"
author: "Elise GUERET"
date: "25 Mai 2018"
adress: "Institut des Sciences de l'Evolution de Montpellier (ISEM), Université de Montpellier, Campus Triolet, Place Eugène Bataillon, cc65, 34095 Montpellier"
output: 
  word_document:
    toc: yes
    reference_docx: word-styles-reference-01.docx
    fig_width: 5
    fig_height: 5
    fig_caption: true
bibliography: Biblio.bib
header-includes: \usepackage[french]{babel}
---
header includes = Pour avoir des noms automatiques d’éléments en français lors de la création d’un document final au format PDF (par exemple le titre de la table des matières)
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Insertion de saut de page Word : <https://datascienceplus.com/r-markdown-how-to-insert-page-breaks-in-a-ms-word-document/>
# Page de couverture 

* les logos  
* intitulé "Mémoire de stage de fin d'études" 
* Elise GUERET 
* Nom des tuteurs
* adresse de la fac
* adresse du stage
* année universitaire en cours
* titre du mémoire

# Remerciements

# Avant-propos

## Table des matières

## Liste des tableaux et des figures

## Liste des abbréviations

# Résumé et mots-clés (en français et en anglais) en 4ème de couverture

# Introduction
Question à se poser avant la rédaction du rapport :   
* Quels étaient les objectifs de mon travail?  
* Quel est le bilan de mon travail?  
* Quelles sont les informations essentielles et les informations secodaires (mais nécessaires) relatives à mon travail?  
* Comment organiser ces informations pour les rendre compréhensilble à un tier?    
Definir le sujet en termes précis et concis, énoncer les objectifs du travail personnel et les moyens mis en oeuvre et présenter le plan adopté pour la suite du sujet d'étude.

Décrire les différents projets européens (RobustBass et CRECHE 2016). Dire à quoi ils servent. Comment les données ont été obtenues? Pour CRECHE voir le rapport dan sles archives ifremer et pour RobustBass voir les dipos KoM.

# Problématique - Objectifs

Replacer le sujet d'études dans un contexte plus général.
Résumer l'état de l'art via une étude des travaux antérieurs.
Présentation du cahier des charges

# Matériels et méthodes

Mettre en valeur l'acquisition d'une technique, d'un savoir-faire enrichissant mes connaissances initiales.
Décrire la méthode ou le logiciel

## Design de l'étude

Description des étapes
Description des données : comment elles ont été obtenues?

## Vue générale des pipelines

Que font-ils ?
Quels outils ou logiciels ils utilisent?

## Description des pipelines

**Penser à impliquer la méthodo c'est-à-dire pour GATK : de comparer les réplicas ainsi que de voir la différence avec des petits bam (peu de reads) et des gros bam (bcp de reads) pour voir si on trouve les mêmes SNPs ou si il y a une différence notable.**
A quoi ils servent?
Mettre un schéma général des principales étapes.

### Correction Annotation par Python

Détails de chaque étape + Schéma

### Data_PreProcessing

Détails de chaque étape + Schéma

### VariantCalling, genotyping and filtering

Détails de chaque étape + Schéma

### Annotation des SNPs

Détails de chaque étape + Schéma

## Liste des outils Picard et GATK

Description de chacun des outils
Quel outil est impliqué dans quelle étape?

## Etude d'association

### Design

Description des étapes (PLINK, ... ) + Schéma

### Population stratification

Expliquer et définir les problèmes de stratification de la population.

# Résultats - Discussion

Avoir un fil conducteur dans un ordre logique pour mettre en évidence un point précis ou un but recherché.

Discussion :  
* Mes résultats sont-ils pertinents?  
* Quelle est leur signification?  
* Quelle en est la portée?  
* Peuvent-ils être utile à d'autres?

## Résultats du génotypage

Parler de Picard et de GATK

## Résultats de l'étude d'association

### Fréquence allèlique et données manquantes
### Estimation de l'"ancestry"
### POpulation stratification
### Top SNPs
### Evaluation des top SNPs
### Analyse fonctionnelle des top SNPs

# Conclusion

Résume le travail accompli et fait apparaître si les objectifs ont été atteints

S'achève par des perspectives ou sur un bilan personnel

* Que dois-je retenir de ce travail?




etblahblah
 Pour la rédaction de doc en Rmd : 
<https://stt4230.rbind.io/communication_resultats/redaction_r_markdown/#creation-dun-document-r-markdown-en-rsudio>

# Options de blocs de code R en R Markdown :
Les options de blocs de code R les plus utiles sont les suivantes :

* ``eval`` (``TRUE`` par défaut, ou ``FALSE``) : détermine si le code R doit être évalué ou non,  
* ``echo`` (``TRUE`` par défaut, ou ``FALSE``) : détermine si le code R doit être affiché ou non,  
* ``results`` (``'markup'`` par défaut, ou ``'hide'`` ou ``'hold'`` ou ``'asis'``) :
détermine comment les sorties doivent être affichées,  
* ``error`` (``FALSE`` par défaut, ou ``TRUE``) : détermine si les messages d’erreur doivent être affichés.  
* ``warning`` (``TRUE`` par défaut, ou ``FALSE``) : détermine si les messages d’avertissement doivent être affichés.  

# References
