---
title: "Reunion du 06/04/2018"
output:
   html_document: 
    fig_caption: yes
    highlight: zenburn
    theme: cerulean
---

* * * * *

# Réunion avec Erick, Bruno et Pierre-Alexandre:

<p style="text-align:justify";>Il faut que je récupère les données de RNA-seq de *Morone saxatilis* dans le but de rechercher les CDS commun afin d'avoir une base d'ID identique pour ensuite trouver/étudier les problèmes de paralogie et d'homologie, cela nous donnera le nombre de comparaison à effectuer. Tout ceci va permettre de donner une mailleure annotation en amont et en aval des gènes. Pour cela il faut que je trouve des outils de transfert d'annotation à partir de données de RNA-seq. Sachant que j'ai à ma disposition les 3 transcriptome de *labrax*, *punctatus* et *saxatilis* ainsi que les génomes alignés de *labrax* et *saxatilis*. La meilleure stratégie serait de récupérer ces transcriptomes, de les aligner puis de faire un BLAT. Les meilleurs outils  pour l'annotation seraient : ``snpEff``, ``VCFanno`` et ``ANNOVAR``. Pour les alignement il faut que je creuse ``TopHat`` et ``Stream`` et ``Bowtie2``. Il faut que je lise les papiers sur les pipelines d'annotation de UCSC datant de 2003, du projet ENCODE et de regarder l'outils ``MAKER2`` dans BMC informatics. Pierre-Alexandre a utilisé les mots clés suivants : genome annotation mRNA (pipeline).</p>
