---
title: "Reunion du 03/04/2018"
output:
   html_document: 
    fig_caption: yes
    highlight: zenburn
    theme: cerulean
---

* * * * * 

# Réunion avec Erick, Bruno et Madoka

<p style="text-align:justify";>Il faut absolument que je fasse l'annotation fonctionnelle des SNP de la puce. Cela va s'avérer très utile pour tout le monde. Voir pour annoter le génome du loup (bar) un peu mieux (surtout au niveau des promoteurs) en alignant avec le génome de *Morone Saxatilis*. Toujours en attente de la commande des puces pour passer les 800 individus avec un budget d'environs 9000€. Mais pour cela il faut encore attendre que le prix soit fini d'être négocié par les différents acteurs impliqués dans les différents projets. Pour faire cette annotation, il faut regarder les outils les plus fréquemment utilisés dans la littérature ainsi que leur fonctionnement sachant que les données seront des données de puces et non de dd-RADseq. D'autre part, si jamais les données n'arrive que trop tard dans mon stage, ils ont des données CRECHE de RNA-seq. Il faudrait donc rechercher les SNP dans ces reads. Les phénotypes sont connus (croissance, tolérance au jeûne). De plus un apparentement des individus serait possible. D'autre part, Il faudrait détailler l'annotation du bar sur le début des gènes et notamment des promoteurs en réalisant par exemple un alignement entre *D_labrax* (voir *D_punctatus*) et *Morone saxatilis*.</p>
